"""
SHAP visualization for the finalized patient-state CAP model.

Creates:
1. Global SHAP feature-importance bar plot
2. SHAP beeswarm plot
3. Individual patient explanation for SEQN 109266

Uses the SHAP values generated by analyze_shap.py.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import shap


# ============================================================
# Paths
# ============================================================

ROOT = Path(__file__).resolve().parents[1]

RESULTS_DIR = ROOT / "data" / "results"

SHAP_VALUES_PATH = (
    RESULTS_DIR / "shap_values.csv"
)

SHAP_IMPORTANCE_PATH = (
    RESULTS_DIR / "shap_feature_importance.csv"
)
SHAP_FEATURES_PATH = (
    RESULTS_DIR / "shap_transformed_features.csv"
)

OUTPUT_DIR = RESULTS_DIR / "shap_plots"

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# Settings
# ============================================================

TOP_N = 20

PATIENT_ID = 109266


# ============================================================
# Load SHAP data
# ============================================================

print("Loading SHAP results...")

shap_values_df = pd.read_csv(
    SHAP_VALUES_PATH
)

importance_df = pd.read_csv(
    SHAP_IMPORTANCE_PATH
)

print(
    f"Loaded SHAP values for "
    f"{len(shap_values_df)} participants."
)

print(
    f"Loaded {len(importance_df)} transformed features."
)

transformed_df = pd.read_csv(
    SHAP_FEATURES_PATH
)

print()


# ============================================================
# Prepare SHAP matrix
# ============================================================

feature_names = [
    column
    for column in shap_values_df.columns
    if column != "SEQN"
]

shap_matrix = shap_values_df[
    feature_names
].to_numpy()

print(
    f"SHAP matrix shape: "
    f"{shap_matrix.shape}"
)

print()


# ============================================================
# 1. Global SHAP bar plot
# ============================================================

print("Creating global SHAP bar plot...")

top_features = (
    importance_df
    .sort_values(
        "mean_abs_shap",
        ascending=False
    )
    .head(TOP_N)
    .sort_values(
        "mean_abs_shap",
        ascending=True
    )
)

plt.figure(
    figsize=(10, 8)
)

plt.barh(
    top_features["feature"],
    top_features["mean_abs_shap"]
)

plt.xlabel(
    "Mean absolute SHAP value"
)

plt.ylabel(
    "Feature"
)

plt.title(
    "Global SHAP Feature Importance"
)

plt.tight_layout()

bar_path = (
    OUTPUT_DIR /
    "shap_global_importance.png"
)

plt.savefig(
    bar_path,
    dpi=300,
    bbox_inches="tight"
)

plt.close()

print(
    f"Saved: {bar_path}"
)

print()


# ============================================================
# 2. SHAP beeswarm plot
# ============================================================

print("Creating SHAP beeswarm plot...")

feature_values = transformed_df[
    feature_names
].to_numpy()

explanation = shap.Explanation(
    values=shap_matrix,
    data=feature_values,
    feature_names=feature_names
)

plt.figure(
    figsize=(11, 9)
)

shap.plots.beeswarm(
    explanation,
    max_display=TOP_N,
    show=False
)

plt.title(
    "SHAP Beeswarm Plot"
)

plt.tight_layout()

beeswarm_path = (
    OUTPUT_DIR /
    "shap_beeswarm.png"
)

plt.savefig(
    beeswarm_path,
    dpi=300,
    bbox_inches="tight"
)

plt.close()

print(
    f"Saved: {beeswarm_path}"
)

print()


# ============================================================
# 3. Individual patient SHAP explanation
# ============================================================

print(
    f"Creating individual explanation "
    f"for SEQN {PATIENT_ID}..."
)

patient_rows = shap_values_df[
    shap_values_df["SEQN"] == PATIENT_ID
]

if patient_rows.empty:

    print(
        f"SEQN {PATIENT_ID} was not found "
        "in the SHAP results."
    )

else:

    patient_index = patient_rows.index[0]

    patient_shap_values = (
        patient_rows[feature_names]
        .iloc[0]
        .to_numpy()
    )

    # Sort by absolute contribution and keep
    # the strongest features.

    patient_order = np.argsort(
        np.abs(patient_shap_values)
    )[::-1][:TOP_N]

    patient_features = [
        feature_names[i]
        for i in patient_order
    ]

    patient_values = [
        patient_shap_values[i]
        for i in patient_order
    ]

    patient_plot_df = pd.DataFrame({
        "feature": patient_features,
        "shap_value": patient_values
    })

    patient_plot_df = (
        patient_plot_df
        .sort_values(
            "shap_value",
            ascending=True
        )
    )

    plt.figure(
        figsize=(10, 8)
    )

    plt.barh(
        patient_plot_df["feature"],
        patient_plot_df["shap_value"]
    )

    plt.axvline(
        0,
        linewidth=1
    )

    plt.xlabel(
        "SHAP contribution to predicted CAP"
    )

    plt.ylabel(
        "Feature"
    )

    plt.title(
        f"Individual SHAP Explanation — "
        f"SEQN {PATIENT_ID}"
    )

    plt.tight_layout()

    patient_path = (
        OUTPUT_DIR /
        f"shap_patient_{PATIENT_ID}.png"
    )

    plt.savefig(
        patient_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    print(
        f"Saved: {patient_path}"
    )

    print()

    print(
        "Top individual feature contributions:"
    )

    print(
        patient_plot_df
        .sort_values(
            "shap_value",
            key=np.abs,
            ascending=False
        )
        .head(10)
        .to_string(index=False)
    )


# ============================================================
# Finished
# ============================================================

print()
print(
    "SHAP visualization generation completed."
)

print(
    f"Output directory: {OUTPUT_DIR}"
)